/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dots;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author natha
 */
public class Opcoes extends javax.swing.JFrame {

	/**
	 * Creates new form TelaExecucao
	 */

	private TelaInicial ti;

	public Opcoes(TelaInicial ti) {
		initComponents();
		this.ti = ti;
		URL iconURL = getClass().getResource("/img/icone.png");
		ImageIcon icon = new ImageIcon(iconURL);
		this.setIconImage(icon.getImage());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		prox1 = new javax.swing.JButton();
		jComboBox1 = new javax.swing.JComboBox<>();
		jLabel5 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox<>();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Dots");
		setMaximumSize(new java.awt.Dimension(478, 250));
		setMinimumSize(new java.awt.Dimension(478, 250));
		setPreferredSize(new java.awt.Dimension(478, 250));
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(204, 204, 204));
		jPanel1.setMaximumSize(new java.awt.Dimension(627, 465));

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel4.setText("Dificuldade:");

		prox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		prox1.setText("Jogar");
		prox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				prox1ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "MinMax", "Heurística", "MonteCarlo" }));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel5.setText("Método:");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(128, 128, 128)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel5).addComponent(jLabel4))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(196, 196, 196).addComponent(prox1)))
						.addContainerGap(151, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(25, 25, 25)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(27, 27, 27)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(35, 35, 35).addComponent(prox1).addContainerGap(72, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void prox1ActionPerformed(java.awt.event.ActionEvent evt) {
		Tabuleiro tab;

		if (jComboBox1.getSelectedItem().toString().equals("MinMax")) {
			tab = new Tabuleiro(new MinMax(jComboBox2.getSelectedIndex() + 1));
		} else if (jComboBox1.getSelectedItem().toString().equals("Heur�stica")) {
			tab = new Tabuleiro(new Heuristica());
		} else {
			tab = new Tabuleiro(new MonteCarlo());
		}

		tab.setVisible(true);
		ti.dispose();
		this.dispose();
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {

		if (!jComboBox1.getSelectedItem().toString().equals("MinMax")) {
			jComboBox2.removeAllItems();
		} else if (jComboBox2.getItemCount() == 0) {
			jComboBox2.addItem("1");
			jComboBox2.addItem("2");
			jComboBox2.addItem("3");
			jComboBox2.addItem("4");
			jComboBox2.addItem("5");
			jComboBox2.addItem("6");
			jComboBox2.addItem("7");
			jComboBox2.addItem("8");
			jComboBox2.addItem("9");
			jComboBox2.addItem("10");
		}

	}

	// Variables declaration - do not modify
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JButton prox1;
	// End of variables declaration
}
