/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dots;

import java.awt.Color;
import java.net.URL;

import javax.swing.ImageIcon;

/**
 *
 * @author 202011020015
 */
public class Tabuleiro extends javax.swing.JFrame {

	private static final int NUM_JOGADAS = 12;

	private static Jogada[] jogadas = new Jogada[NUM_JOGADAS];
	private static boolean multiplayerFlag = true;
	private static Ia ia;
	private static boolean multiplayer;
	private static Tabuleiro tab;
	private static int count = 0;

	/**
	 * Creates new form Main
	 */
	public Tabuleiro(Ia ia) {
		initComponents();
		this.setTitle("Dots");
		URL iconURL = getClass().getResource("/img/icone.png");
		ImageIcon icon = new ImageIcon(iconURL);
		this.setIconImage(icon.getImage());
		Tabuleiro.ia = ia;
		tab = this;
		if (ia == null)
			multiplayer = true;
		else {
			multiplayer = false;
			ia.jogadaInicial();
		}
	}

	public Ia getIA() {
		return ia;
	}

	public static void setenable(boolean flag) {
		tab.setEnabled(flag);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		q2 = new javax.swing.JPanel();
		t2 = new javax.swing.JLabel();
		jPanel27 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		q4 = new javax.swing.JPanel();
		t4 = new javax.swing.JLabel();
		jPanel29 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		q9 = new javax.swing.JPanel();
		q10 = new javax.swing.JPanel();
		t10 = new javax.swing.JLabel();
		q6 = new javax.swing.JPanel();
		t6 = new javax.swing.JLabel();
		q7 = new javax.swing.JPanel();
		q8 = new javax.swing.JPanel();
		t8 = new javax.swing.JLabel();
		jPanel37 = new javax.swing.JPanel();
		jLabel13 = new javax.swing.JLabel();
		q12 = new javax.swing.JPanel();
		t12 = new javax.swing.JLabel();
		jPanel35 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		jPanel39 = new javax.swing.JPanel();
		jLabel15 = new javax.swing.JLabel();
		q14 = new javax.swing.JPanel();
		t14 = new javax.swing.JLabel();
		q18 = new javax.swing.JPanel();
		t18 = new javax.swing.JLabel();
		q17 = new javax.swing.JPanel();
		q16 = new javax.swing.JPanel();
		t16 = new javax.swing.JLabel();
		q20 = new javax.swing.JPanel();
		t20 = new javax.swing.JLabel();
		q19 = new javax.swing.JPanel();
		jPanel45 = new javax.swing.JPanel();
		jLabel21 = new javax.swing.JLabel();
		jPanel47 = new javax.swing.JPanel();
		jLabel23 = new javax.swing.JLabel();
		q22 = new javax.swing.JPanel();
		t22 = new javax.swing.JLabel();
		jPanel49 = new javax.swing.JPanel();
		jLabel25 = new javax.swing.JLabel();
		q24 = new javax.swing.JPanel();
		t24 = new javax.swing.JLabel();

		jTable1.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(500, 500));
		setPreferredSize(new java.awt.Dimension(504, 527));
		setResizable(false);
		getContentPane().setLayout(null);

		jPanel1.setBackground(new java.awt.Color(153, 102, 0));
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		jLabel1.setText(".");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel1)
						.addContainerGap(43, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addContainerGap(29, Short.MAX_VALUE)));

		getContentPane().add(jPanel1);
		jPanel1.setBounds(0, 0, 100, 100);

		q2.setBackground(new java.awt.Color(153, 102, 0));
		q2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q2.setPreferredSize(new java.awt.Dimension(100, 100));
		q2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q2MouseClicked(evt);
			}
		});

		t2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t2.setText("__");

		javax.swing.GroupLayout q2Layout = new javax.swing.GroupLayout(q2);
		q2.setLayout(q2Layout);
		q2Layout.setHorizontalGroup(q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q2Layout.createSequentialGroup().addGap(22, 22, 22).addComponent(t2).addContainerGap(24,
						Short.MAX_VALUE)));
		q2Layout.setVerticalGroup(q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q2Layout.createSequentialGroup().addComponent(t2).addGap(0, 40, Short.MAX_VALUE)));

		getContentPane().add(q2);
		q2.setBounds(100, 0, 100, 100);

		jPanel27.setBackground(new java.awt.Color(153, 102, 0));
		jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel27.setPreferredSize(new java.awt.Dimension(100, 100));

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		jLabel3.setText(".");

		javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
		jPanel27.setLayout(jPanel27Layout);
		jPanel27Layout.setHorizontalGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel27Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel3)
						.addContainerGap(43, Short.MAX_VALUE)));
		jPanel27Layout.setVerticalGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel27Layout.createSequentialGroup().addContainerGap().addComponent(jLabel3)
						.addContainerGap(29, Short.MAX_VALUE)));

		getContentPane().add(jPanel27);
		jPanel27.setBounds(200, 0, 100, 100);

		q4.setBackground(new java.awt.Color(153, 102, 0));
		q4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q4.setPreferredSize(new java.awt.Dimension(100, 100));
		q4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q4MouseClicked(evt);
			}
		});

		t4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t4.setText("__");

		javax.swing.GroupLayout q4Layout = new javax.swing.GroupLayout(q4);
		q4.setLayout(q4Layout);
		q4Layout.setHorizontalGroup(q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, q4Layout.createSequentialGroup()
						.addContainerGap(23, Short.MAX_VALUE).addComponent(t4).addGap(23, 23, 23)));
		q4Layout.setVerticalGroup(q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q4Layout.createSequentialGroup().addComponent(t4).addGap(0, 40, Short.MAX_VALUE)));

		getContentPane().add(q4);
		q4.setBounds(300, 0, 100, 100);

		jPanel29.setBackground(new java.awt.Color(153, 102, 0));
		jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel29.setPreferredSize(new java.awt.Dimension(100, 100));

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		jLabel5.setText(".");

		javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
		jPanel29.setLayout(jPanel29Layout);
		jPanel29Layout.setHorizontalGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel29Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel5)
						.addContainerGap(43, Short.MAX_VALUE)));
		jPanel29Layout.setVerticalGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel29Layout.createSequentialGroup().addContainerGap().addComponent(jLabel5)
						.addContainerGap(29, Short.MAX_VALUE)));

		getContentPane().add(jPanel29);
		jPanel29.setBounds(400, 0, 100, 100);

		q9.setBackground(new java.awt.Color(153, 102, 0));
		q9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q9.setPreferredSize(new java.awt.Dimension(100, 100));

		javax.swing.GroupLayout q9Layout = new javax.swing.GroupLayout(q9);
		q9.setLayout(q9Layout);
		q9Layout.setHorizontalGroup(
				q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 98, Short.MAX_VALUE));
		q9Layout.setVerticalGroup(
				q9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 98, Short.MAX_VALUE));

		getContentPane().add(q9);
		q9.setBounds(300, 100, 100, 100);

		q10.setBackground(new java.awt.Color(153, 102, 0));
		q10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q10.setPreferredSize(new java.awt.Dimension(100, 100));
		q10.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q10MouseClicked(evt);
			}
		});

		t10.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t10.setText("|");

		javax.swing.GroupLayout q10Layout = new javax.swing.GroupLayout(q10);
		q10.setLayout(q10Layout);
		q10Layout.setHorizontalGroup(q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q10Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(t10).addContainerGap(40,
						Short.MAX_VALUE)));
		q10Layout.setVerticalGroup(q10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q10Layout.createSequentialGroup().addContainerGap().addComponent(t10).addContainerGap(29,
						Short.MAX_VALUE)));

		getContentPane().add(q10);
		q10.setBounds(400, 100, 100, 100);

		q6.setBackground(new java.awt.Color(153, 102, 0));
		q6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q6.setPreferredSize(new java.awt.Dimension(100, 100));
		q6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q6MouseClicked(evt);
			}
		});

		t6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t6.setText("|");

		javax.swing.GroupLayout q6Layout = new javax.swing.GroupLayout(q6);
		q6.setLayout(q6Layout);
		q6Layout.setHorizontalGroup(q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q6Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(t6).addContainerGap(40,
						Short.MAX_VALUE)));
		q6Layout.setVerticalGroup(q6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q6Layout.createSequentialGroup().addContainerGap().addComponent(t6).addContainerGap(29,
						Short.MAX_VALUE)));

		getContentPane().add(q6);
		q6.setBounds(0, 100, 100, 100);

		q7.setBackground(new java.awt.Color(153, 102, 0));
		q7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q7.setPreferredSize(new java.awt.Dimension(100, 100));

		javax.swing.GroupLayout q7Layout = new javax.swing.GroupLayout(q7);
		q7.setLayout(q7Layout);
		q7Layout.setHorizontalGroup(
				q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 98, Short.MAX_VALUE));
		q7Layout.setVerticalGroup(
				q7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 98, Short.MAX_VALUE));

		getContentPane().add(q7);
		q7.setBounds(100, 100, 100, 100);

		q8.setBackground(new java.awt.Color(153, 102, 0));
		q8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q8.setPreferredSize(new java.awt.Dimension(100, 100));
		q8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q8MouseClicked(evt);
			}
		});

		t8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t8.setText("|");

		javax.swing.GroupLayout q8Layout = new javax.swing.GroupLayout(q8);
		q8.setLayout(q8Layout);
		q8Layout.setHorizontalGroup(q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q8Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(t8).addContainerGap(40,
						Short.MAX_VALUE)));
		q8Layout.setVerticalGroup(q8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q8Layout.createSequentialGroup().addContainerGap().addComponent(t8).addContainerGap(29,
						Short.MAX_VALUE)));

		getContentPane().add(q8);
		q8.setBounds(200, 100, 100, 100);

		jPanel37.setBackground(new java.awt.Color(153, 102, 0));
		jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel37.setPreferredSize(new java.awt.Dimension(100, 100));

		jLabel13.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		jLabel13.setText(".");

		javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
		jPanel37.setLayout(jPanel37Layout);
		jPanel37Layout.setHorizontalGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel37Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel13)
						.addContainerGap(43, Short.MAX_VALUE)));
		jPanel37Layout.setVerticalGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel37Layout.createSequentialGroup().addContainerGap().addComponent(jLabel13)
						.addContainerGap(29, Short.MAX_VALUE)));

		getContentPane().add(jPanel37);
		jPanel37.setBounds(200, 200, 100, 100);

		q12.setBackground(new java.awt.Color(153, 102, 0));
		q12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q12.setPreferredSize(new java.awt.Dimension(100, 100));
		q12.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q12MouseClicked(evt);
			}
		});

		t12.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t12.setText("__");

		javax.swing.GroupLayout q12Layout = new javax.swing.GroupLayout(q12);
		q12.setLayout(q12Layout);
		q12Layout.setHorizontalGroup(q12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q12Layout.createSequentialGroup().addGap(22, 22, 22).addComponent(t12).addContainerGap(24,
						Short.MAX_VALUE)));
		q12Layout.setVerticalGroup(q12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q12Layout.createSequentialGroup().addComponent(t12).addGap(0, 40, Short.MAX_VALUE)));

		getContentPane().add(q12);
		q12.setBounds(100, 200, 100, 100);

		jPanel35.setBackground(new java.awt.Color(153, 102, 0));
		jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel35.setPreferredSize(new java.awt.Dimension(100, 100));

		jLabel11.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		jLabel11.setText(".");

		javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
		jPanel35.setLayout(jPanel35Layout);
		jPanel35Layout.setHorizontalGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel35Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel11)
						.addContainerGap(43, Short.MAX_VALUE)));
		jPanel35Layout.setVerticalGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel35Layout.createSequentialGroup().addContainerGap().addComponent(jLabel11)
						.addContainerGap(29, Short.MAX_VALUE)));

		getContentPane().add(jPanel35);
		jPanel35.setBounds(0, 200, 100, 100);

		jPanel39.setBackground(new java.awt.Color(153, 102, 0));
		jPanel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel39.setPreferredSize(new java.awt.Dimension(100, 100));

		jLabel15.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		jLabel15.setText(".");

		javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
		jPanel39.setLayout(jPanel39Layout);
		jPanel39Layout.setHorizontalGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel39Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel15)
						.addContainerGap(43, Short.MAX_VALUE)));
		jPanel39Layout.setVerticalGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel39Layout.createSequentialGroup().addContainerGap().addComponent(jLabel15)
						.addContainerGap(29, Short.MAX_VALUE)));

		getContentPane().add(jPanel39);
		jPanel39.setBounds(400, 200, 100, 100);

		q14.setBackground(new java.awt.Color(153, 102, 0));
		q14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q14.setPreferredSize(new java.awt.Dimension(100, 100));
		q14.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q14MouseClicked(evt);
			}
		});

		t14.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t14.setText("__");

		javax.swing.GroupLayout q14Layout = new javax.swing.GroupLayout(q14);
		q14.setLayout(q14Layout);
		q14Layout.setHorizontalGroup(q14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q14Layout.createSequentialGroup().addGap(23, 23, 23).addComponent(t14).addContainerGap(23,
						Short.MAX_VALUE)));
		q14Layout.setVerticalGroup(q14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q14Layout.createSequentialGroup().addComponent(t14).addGap(0, 40, Short.MAX_VALUE)));

		getContentPane().add(q14);
		q14.setBounds(300, 200, 100, 100);

		q18.setBackground(new java.awt.Color(153, 102, 0));
		q18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q18.setPreferredSize(new java.awt.Dimension(100, 100));
		q18.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q18MouseClicked(evt);
			}
		});

		t18.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t18.setText("|");

		javax.swing.GroupLayout q18Layout = new javax.swing.GroupLayout(q18);
		q18.setLayout(q18Layout);
		q18Layout.setHorizontalGroup(q18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q18Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(t18).addContainerGap(40,
						Short.MAX_VALUE)));
		q18Layout.setVerticalGroup(q18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q18Layout.createSequentialGroup().addContainerGap().addComponent(t18).addContainerGap(29,
						Short.MAX_VALUE)));

		getContentPane().add(q18);
		q18.setBounds(200, 300, 100, 100);

		q17.setBackground(new java.awt.Color(153, 102, 0));
		q17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q17.setPreferredSize(new java.awt.Dimension(100, 100));

		javax.swing.GroupLayout q17Layout = new javax.swing.GroupLayout(q17);
		q17.setLayout(q17Layout);
		q17Layout.setHorizontalGroup(q17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
				98, Short.MAX_VALUE));
		q17Layout.setVerticalGroup(q17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
				98, Short.MAX_VALUE));

		getContentPane().add(q17);
		q17.setBounds(100, 300, 100, 100);

		q16.setBackground(new java.awt.Color(153, 102, 0));
		q16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q16.setPreferredSize(new java.awt.Dimension(100, 100));
		q16.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q16MouseClicked(evt);
			}
		});

		t16.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t16.setText("|");

		javax.swing.GroupLayout q16Layout = new javax.swing.GroupLayout(q16);
		q16.setLayout(q16Layout);
		q16Layout.setHorizontalGroup(q16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q16Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(t16).addContainerGap(40,
						Short.MAX_VALUE)));
		q16Layout.setVerticalGroup(q16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q16Layout.createSequentialGroup().addContainerGap().addComponent(t16).addContainerGap(29,
						Short.MAX_VALUE)));

		getContentPane().add(q16);
		q16.setBounds(0, 300, 100, 100);

		q20.setBackground(new java.awt.Color(153, 102, 0));
		q20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q20.setPreferredSize(new java.awt.Dimension(100, 100));
		q20.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q20MouseClicked(evt);
			}
		});

		t20.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t20.setText("|");

		javax.swing.GroupLayout q20Layout = new javax.swing.GroupLayout(q20);
		q20.setLayout(q20Layout);
		q20Layout.setHorizontalGroup(q20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q20Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(t20).addContainerGap(40,
						Short.MAX_VALUE)));
		q20Layout.setVerticalGroup(q20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q20Layout.createSequentialGroup().addContainerGap().addComponent(t20).addContainerGap(29,
						Short.MAX_VALUE)));

		getContentPane().add(q20);
		q20.setBounds(400, 300, 100, 100);

		q19.setBackground(new java.awt.Color(153, 102, 0));
		q19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q19.setPreferredSize(new java.awt.Dimension(100, 100));

		javax.swing.GroupLayout q19Layout = new javax.swing.GroupLayout(q19);
		q19.setLayout(q19Layout);
		q19Layout.setHorizontalGroup(q19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
				98, Short.MAX_VALUE));
		q19Layout.setVerticalGroup(q19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
				98, Short.MAX_VALUE));

		getContentPane().add(q19);
		q19.setBounds(300, 300, 100, 100);

		jPanel45.setBackground(new java.awt.Color(153, 102, 0));
		jPanel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel45.setPreferredSize(new java.awt.Dimension(100, 100));

		jLabel21.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		jLabel21.setText(".");

		javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
		jPanel45.setLayout(jPanel45Layout);
		jPanel45Layout.setHorizontalGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel45Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel21)
						.addContainerGap(43, Short.MAX_VALUE)));
		jPanel45Layout.setVerticalGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel45Layout.createSequentialGroup().addContainerGap().addComponent(jLabel21)
						.addContainerGap(29, Short.MAX_VALUE)));

		getContentPane().add(jPanel45);
		jPanel45.setBounds(0, 400, 100, 100);

		jPanel47.setBackground(new java.awt.Color(153, 102, 0));
		jPanel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel47.setPreferredSize(new java.awt.Dimension(100, 100));

		jLabel23.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		jLabel23.setText(".");

		javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
		jPanel47.setLayout(jPanel47Layout);
		jPanel47Layout.setHorizontalGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel47Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel23)
						.addContainerGap(43, Short.MAX_VALUE)));
		jPanel47Layout.setVerticalGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel47Layout.createSequentialGroup().addContainerGap().addComponent(jLabel23)
						.addContainerGap(29, Short.MAX_VALUE)));

		getContentPane().add(jPanel47);
		jPanel47.setBounds(200, 400, 100, 100);

		q22.setBackground(new java.awt.Color(153, 102, 0));
		q22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q22.setPreferredSize(new java.awt.Dimension(100, 100));
		q22.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q22MouseClicked(evt);
			}
		});

		t22.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t22.setText("__");

		javax.swing.GroupLayout q22Layout = new javax.swing.GroupLayout(q22);
		q22.setLayout(q22Layout);
		q22Layout.setHorizontalGroup(q22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q22Layout.createSequentialGroup().addGap(21, 21, 21).addComponent(t22).addContainerGap(25,
						Short.MAX_VALUE)));
		q22Layout.setVerticalGroup(q22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q22Layout.createSequentialGroup().addComponent(t22).addGap(0, 40, Short.MAX_VALUE)));

		getContentPane().add(q22);
		q22.setBounds(100, 400, 100, 100);

		jPanel49.setBackground(new java.awt.Color(153, 102, 0));
		jPanel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel49.setPreferredSize(new java.awt.Dimension(100, 100));

		jLabel25.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		jLabel25.setText(".");

		javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
		jPanel49.setLayout(jPanel49Layout);
		jPanel49Layout.setHorizontalGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel49Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel25)
						.addContainerGap(43, Short.MAX_VALUE)));
		jPanel49Layout.setVerticalGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel49Layout.createSequentialGroup().addContainerGap().addComponent(jLabel25)
						.addContainerGap(29, Short.MAX_VALUE)));

		getContentPane().add(jPanel49);
		jPanel49.setBounds(400, 400, 100, 100);

		q24.setBackground(new java.awt.Color(153, 102, 0));
		q24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		q24.setPreferredSize(new java.awt.Dimension(100, 100));
		q24.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				q24MouseClicked(evt);
			}
		});

		t24.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
		t24.setText("__");

		javax.swing.GroupLayout q24Layout = new javax.swing.GroupLayout(q24);
		q24.setLayout(q24Layout);
		q24Layout.setHorizontalGroup(q24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q24Layout.createSequentialGroup().addGap(24, 24, 24).addComponent(t24).addContainerGap(22,
						Short.MAX_VALUE)));
		q24Layout.setVerticalGroup(q24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(q24Layout.createSequentialGroup().addComponent(t24).addGap(0, 40, Short.MAX_VALUE)));

		getContentPane().add(q24);
		q24.setBounds(300, 400, 100, 100);

		pack();
		setLocationRelativeTo(null);

		t2.setVisible(false);
		t4.setVisible(false);
		t6.setVisible(false);
		t8.setVisible(false);
		t10.setVisible(false);
		t12.setVisible(false);
		t14.setVisible(false);
		t16.setVisible(false);
		t18.setVisible(false);
		t20.setVisible(false);
		t22.setVisible(false);
		t24.setVisible(false);

		javax.swing.JPanel[] colorir = new javax.swing.JPanel[2];

		colorir[0] = q7;
		jogadas[0] = new Jogada(q2, t2, colorir.clone(), t6, t8, t12);

		colorir[0] = q9;
		jogadas[1] = new Jogada(q4, t4, colorir.clone(), t8, t10, t14);

		colorir[0] = q7;
		jogadas[2] = new Jogada(q6, t6, colorir.clone(), t2, t8, t12);

		colorir[0] = q7;
		colorir[1] = q9;
		jogadas[3] = new Jogada(q8, t8, colorir.clone(), t6, t2, t12, t4, t10, t14);

		colorir[0] = q9;
		jogadas[4] = new Jogada(q10, t10, colorir.clone(), t4, t8, t14);

		colorir[0] = q7;
		colorir[1] = q17;
		jogadas[5] = new Jogada(q12, t12, colorir.clone(), t6, t2, t8, t16, t18, t22);

		colorir[0] = q9;
		colorir[1] = q19;
		jogadas[6] = new Jogada(q14, t14, colorir.clone(), t4, t10, t8, t24, t18, t20);

		colorir[0] = q17;
		jogadas[7] = new Jogada(q16, t16, colorir.clone(), t12, t18, t22);

		colorir[0] = q17;
		colorir[1] = q19;
		jogadas[8] = new Jogada(q18, t18, colorir.clone(), t12, t16, t22, t14, t24, t20);

		colorir[0] = q19;
		jogadas[9] = new Jogada(q20, t20, colorir.clone(), t14, t18, t24);

		colorir[0] = q17;
		jogadas[10] = new Jogada(q22, t22, colorir.clone(), t12, t18, t16);

		colorir[0] = q19;
		jogadas[11] = new Jogada(q24, t24, colorir.clone(), t14, t18, t20);
	}// </editor-fold>

	public static boolean fazerJogada(int id, boolean maquina) {
		tab.setEnabled(false);
		if (!multiplayer) {
			if(ia.getClass().equals(MinMax.class)) {
				MinMax.percorrerArvore(id);
			}
			else if(ia.getClass().equals(Heuristica.class)){
				Heuristica.percorrerArvore(id);
			}
			else {
				MonteCarlo.atualizar(id);
			}
		}

		count++;
		Jogada j = jogadas[id];
		javax.swing.JLabel[] vizinhos = j.getVizinhos();
		boolean ponto = false;

		j.getLabelAlvo().setVisible(true);

		if (vizinhos[0].isVisible() && vizinhos[1].isVisible() && vizinhos[2].isVisible()) {
			ponto = true;
			if (maquina) {
				j.getColorir()[0].setBackground(new Color(153, 153, 255));
			} else {
				j.getColorir()[0].setBackground(new Color(255, 102, 102));
			}
		}
		if (vizinhos.length > 3) {
			if (vizinhos[3].isVisible() && vizinhos[4].isVisible() && vizinhos[5].isVisible()) {
				ponto = true;
				if (maquina) {
					j.getColorir()[1].setBackground(new Color(153, 153, 255));
				} else {
					j.getColorir()[1].setBackground(new Color(255, 102, 102));
				}
			}
		}

		j.getQuadradoAlvo().removeMouseListener(j.getQuadradoAlvo().getMouseListeners()[0]);

		tab.setEnabled(true);

		if (count == NUM_JOGADAS) {
			if (!multiplayer)
				ia.finalizar();
			count = 0;
			new TelaFinal(tab).setVisible(true);
			return maquina ? false : true;
		}

		if (!ponto) {
			return false;
		} else {
			return true;
		}
	}

	private void q2MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(0, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	private void q4MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(1, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	private void q6MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(2, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	private void q8MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(3, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	private void q10MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(4, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	private void q12MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(5, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	private void q14MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(6, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	private void q16MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(7, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	private void q18MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(8, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	private void q20MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(9, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	private void q22MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(10, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	private void q24MouseClicked(java.awt.event.MouseEvent evt) {
		new Thread(() -> {
			boolean flag = fazerJogada(11, multiplayer ? multiplayerFlag : false);

			if (!flag) {
				if (multiplayer) {
					multiplayerFlag = !multiplayerFlag;
				} else {
					ia.jogada();
				}
			}

		}).start();
	}

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify
	public static javax.swing.JLabel jLabel1;
	public static javax.swing.JLabel t10;
	public static javax.swing.JLabel jLabel11;
	public static javax.swing.JLabel t12;
	public static javax.swing.JLabel jLabel13;
	public static javax.swing.JLabel t14;
	public static javax.swing.JLabel jLabel15;
	public static javax.swing.JLabel t16;
	public static javax.swing.JLabel t18;
	public static javax.swing.JLabel t2;
	public static javax.swing.JLabel t20;
	public static javax.swing.JLabel jLabel21;
	public static javax.swing.JLabel t22;
	public static javax.swing.JLabel jLabel23;
	public static javax.swing.JLabel t24;
	public static javax.swing.JLabel jLabel25;
	public static javax.swing.JLabel jLabel3;
	public static javax.swing.JLabel t4;
	public static javax.swing.JLabel jLabel5;
	public static javax.swing.JLabel t6;
	public static javax.swing.JLabel t8;
	public static javax.swing.JPanel jPanel1;
	public static javax.swing.JPanel q2;
	public static javax.swing.JPanel jPanel27;
	public static javax.swing.JPanel q4;
	public static javax.swing.JPanel jPanel29;
	public static javax.swing.JPanel q6;
	public static javax.swing.JPanel q7;
	public static javax.swing.JPanel q8;
	public static javax.swing.JPanel q9;
	public static javax.swing.JPanel q10;
	public static javax.swing.JPanel jPanel35;
	public static javax.swing.JPanel q12;
	public static javax.swing.JPanel jPanel37;
	public static javax.swing.JPanel q14;
	public static javax.swing.JPanel jPanel39;
	public static javax.swing.JPanel q16;
	public static javax.swing.JPanel q17;
	public static javax.swing.JPanel q18;
	public static javax.swing.JPanel q19;
	public static javax.swing.JPanel q20;
	public static javax.swing.JPanel jPanel45;
	public static javax.swing.JPanel q22;
	public static javax.swing.JPanel jPanel47;
	public static javax.swing.JPanel q24;
	public static javax.swing.JPanel jPanel49;
	public static javax.swing.JScrollPane jScrollPane1;
	public static javax.swing.JTable jTable1;
	// End of variables declaration
}